### ISSUE TITLE
add travis CI

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-merkle-dag#11]

**Comment by vijayee** [comment]
ambiguous issue is ambiguous. I'll have to figure out Travis.

**Comment by vijayee** [comment]
Travis has been added https://github.com/vijayee/js-ipfs-merkle-dag/commit/c6f0d8e5fe200bff3125a0920938aad8d5645bc0

**Comment by daviddias** [comment]
sweet! :D
