### ISSUE TITLE
CumulativeSize

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-merkle-dag#16]
We need this for `ipfs object stat` https://github.com/ipfs/go-ipfs/blob/master/merkledag/pb/merkledag.proto#L27-L28

**Comment by vijayee** [comment]
I don't understand we should already be storing this metadata

**Comment by rht** [comment]
Indeed, the PBLink cumulative size has already been specified https://github.com/vijayee/js-ipfs-merkle-dag/blob/4c3c39a1327f5d1e77ecb78e399ddedf85eda3f2/src/dag-node.js#L4

**Comment by rht** [comment]
(@diasdavid immutable link to the line should be used for proper archival)

**Comment by daviddias** [comment]
> I don't understand we should already be storing this metadata
> Indeed, the PBLink cumulative size has already been specified https://github.com/vijayee/js-ipfs-merkle-dag/blob/4c3c39a1327f5d1e77ecb78e399ddedf85eda3f2/src/dag-node.js#L4

It lives on the .proto schema, but it is not accessible through the JS API for the MerkleDAG obj, that is what I meant we need :) 

> (@diasdavid immutable link to the line should be used for proper archival)

Didn't get it, mind illustrating what you meant?

**Comment by rht** [comment]
The link size appears to be accessible, e.g. in https://github.com/vijayee/js-ipfs-merkle-dag/blob/4c3c39a1327f5d1e77ecb78e399ddedf85eda3f2/src/dag-node.js#L126.
It just needs to be put into the API.

For my next comment, it's just a reminder. I was referring to the link to the code lines you cited, https://github.com/ipfs/go-ipfs/blob/master/merkledag/pb/merkledag.proto#L27-L28, which are mutable and might not anchor to the lines correctly when the `merkledag.proto` gets updated. (though I find it tedious to have to refer to a specific commit each time. For this, I think github could auto-convert the link based on the time-stamp of the comment or something)

**Comment by daviddias** [comment]
Hey @vijayee! This module has been deprecated in favour of [ipld-dag-pb](https://github.com/ipld/js-ipld-dag-pb) and [ipld-resolver](https://github.com/ipld/js-ipld-resolver), see:

https://github.com/ipfs/js-ipfs-merkle-dag#deprecatedjs-ipfs-merkle-dag

Closing this issue :)
