### ISSUE TITLE
remove link by hash

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-merkle-dag#19]
it would be cool to have a similar helper but to remove the link by the hash it is pointing to: https://github.com/vijayee/js-ipfs-merkle-dag/blob/master/src/dag-node.js#L68-L78

**Comment by vijayee** [comment]
Do we want to replace this method with hashes or add a new different method? I ask because it seems like names are deprecated across the board.

**Comment by daviddias** [comment]
I'm not sure what you mean by "link names" being deprecated. I was proposing to have an additional method.

**Comment by vijayee** [comment]
This should be implemented and tested now so I'm going to close the issue

**Comment by daviddias** [comment]
Thank you @vijayee :)
