### ISSUE TITLE
Traversals should be.... streams

### ISSUE THREAD

**Issue by vijayee** [ipfs/js-ipfs-merkle-dag#20]
Seems like moi y @diasdavid  got out of sync while I was implementing the traversals. Links no longer posess their nodes as a part of their properties. Which makes my completed iterator based approach...worthless (juxtaposition synchronous for the most part). I'm going to rewrite this in a stream pattern. Sound good?

**Comment by daviddias** [comment]
Apologies @vijayee, didn't want to break your traversals code, the MerkleDAG API that is implemented right now is pretty stable, I would say, but we can always add more stuff. What would you like to achieve with these 'traversals'? If you describe it, it will help getting all the pieces in place from API levels to internals. 

@vijayee following @whyrusleeping comment https://github.com/ipfs/go-ipfs/issues/2262#issuecomment-177064533, seems like that pointer to the node is not quite used for graph operations.

**Comment by daviddias** [comment]
Hey @vijayee! This module has been deprecated in favour of [ipld-dag-pb](https://github.com/ipld/js-ipld-dag-pb) and [ipld-resolver](https://github.com/ipld/js-ipld-resolver), see:

https://github.com/ipfs/js-ipfs-merkle-dag#deprecatedjs-ipfs-merkle-dag

Closing this issue :)
