### ISSUE TITLE
Rename to js-ipfs-merkle-dag

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-merkle-dag#4]
Would you mind renaming the repo to `js-ipfs-merkle-dag` to match all the JavaScript/Node.js repos we have on the IPFS project?
- We need to get this to npm, could you publish it as a patch version as share ownership on npm with me, my user on npm is `daviddias`?

**Comment by vijayee** [comment]
I totally agree. When I started this I had no idea it might be shared with actual ipfs so it wasn't considered. I'll try to do this today.

**Comment by daviddias** [comment]
Thank you :)

for reference https://www.npmjs.com/package/ipfs-merkle-dag
