### ISSUE TITLE
Provide a dist that is compatible with browsers

### ISSUE THREAD

**Issue by chmanie** [ipfs/js-ipfs-merkle-dag#41]
This package is used as a dependency in https://github.com/ipfs/js-ipfs-api. It claims to be able to run in the browser but in fact, it does not because this package is using the node-only 'fs' library.

Is it possible to create a dist and inline the 'merkledag.proto' at compile time?

**Comment by dignifiedquire** [comment]
This is already being done. If you install from npm there is a `dist/index.js` file which has everything inlined and should be ready for browser consumption.

**Comment by chmanie** [comment]
Great! Thanks a lot! But for that to be considered by npm you'd have to change the "main" entry in the package.json to "dist/index.js".

**Comment by dignifiedquire** [comment]
You can require it using `ipfs-merkle-dag/dist`. We won't set it as `main` because that is being used by node.js and browserify and webpack to load the non bundled version for processing as a default.

**Comment by chmanie** [comment]
Ah OK, makes sense! Thanks

**Comment by daviddias** [comment]
Let us know if you run into any other obstacle :) Closing this one, reopen if needed.
