### ISSUE TITLE
Moving to ipfs github org

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-merkle-dag#42]
I think it would be great if we can move this repo to the `ipfs` github organization, for discoverability and ease of management. @vijayee you would of course maintain all administrative rights that you have currently.

**Comment by vijayee** [comment]
Knock yourself out. I think that is best.

**Comment by dignifiedquire** [comment]
@diasdavid could you do this? I think you already have all the needed permissions on the org as well as on this repo

**Comment by daviddias** [comment]
nvm me :) ~~Hi @vijayee, I believe that @dignifiedquire means is that by having all the pieces of IPFS under the IPFS org, it will be easier for others to find the modules, contribute and know who is actively contributing to the project (i.e: you). Note that he didn't mean to take the ownership of this module away from you, you will keep the authorship and of course, push rights.~~

Anyways, I'm super thankful for your contribution and for leading this endeavour, feel free to decide what is best :) 

~~@dignifiedquire I'm not overwriting the authors intention.~~

**Comment by dignifiedquire** [comment]
Sorry, I'm confused now. I understood @vijayee comment as such that he is okay with the transfer.

**Comment by daviddias** [comment]
Oh! I'm the one who got it wrong, idioms :) nvm me then!

It has to be @vijayee moving to the org, I just have push rights.

**Comment by vijayee** [comment]
I'm a little confused too but I think we are all on the same page. Move it over. Keep up the good work and let me know if you need anything.

**Comment by vijayee** [comment]
@diasdavid  can I move it if I'm not apart of the organization??

**Comment by daviddias** [comment]
I guess that the way to do it is that you move it to me and then I move it to the org.

**Comment by dignifiedquire** [comment]
Thank you @vijayee for working through this "quick and easy process"

Left to do 
- [x] Update references in the readme and package.json

**Comment by daviddias** [comment]
releasing a patch version now. Thank you all :)
