### ISSUE TITLE
Enable support for other hashes

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-merkle-dag#49]
Add an option on the function for encoding to enable support for other hashes. 

Priority: sha3; Goal: So that it is useful for https://github.com/ethereumjs/merkle-patricia-tree

Ref: https://github.com/ethereumjs/merkle-patricia-tree/issues/13

**Comment by dignifiedquire** [comment]
I've been doing lots of crypto experiments, will take care of this.

**Comment by dignifiedquire** [comment]
Step 1: Adding sha3 support to multihashing: https://github.com/multiformats/js-multihashing/pull/12

**Comment by dignifiedquire** [comment]
@diasdavid What api are we looking at here? Should this be a general parameter to the constructor of `DAGNode` or just a parameter to `.encode`?

**Comment by dignifiedquire** [comment]
Nvm it's actually pretty straight forward, the important api change is in `dagnode.multihash` see #50 for details.

**Comment by daviddias** [comment]
It is now possible with IPLD and CID wooooooo!

Also, for those watching, this module has been deprecated in favour of [ipld-dag-pb](https://github.com/ipld/js-ipld-dag-pb) and [ipld-resolver](https://github.com/ipld/js-ipld-resolver), see:

https://github.com/ipfs/js-ipfs-merkle-dag#deprecatedjs-ipfs-merkle-dag

Closing this issue :)
