### ISSUE TITLE
link sorting should be by chunk order and not by name

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-merkle-dag#8]
https://github.com/vijayee/js-ipfs-merkle-dag/blob/master/src/dag-node.js#L20-L22

**Comment by vijayee** [comment]
This is how it is in go IPFS.
https://github.com/ipfs/go-ipfs/blob/master/merkledag/node.go#L60
 I haven't seen any metadata relative to chunk order. They do serialize differently based on link order. Let me know how to implement this.

**Comment by daviddias** [comment]
Not sure how that is used in go-ipfs, but @whyrusleeping can confirm. Link order to data nodes is done at the chunking level and stays immutable.

**Comment by vijayee** [comment]
@whyrusleeping.... I need information on chunking and on how the sort and name features are used on links in go-ipfs.

**Comment by whyrusleeping** [comment]
we do a stable sort by the name of the link

**Comment by vijayee** [comment]
I feel like this (GH-18) punctuates the end of an overly complicated sentence that @diasdavid, @whyrusleeping and myself are trying to say. But its meaning is that we don't need link sorting at all. They go in the order they were placed and that is all there is to it. Is this correct? Furthermore, this also suggests the name field in the link object is also not needed?

**Comment by rht** [comment]
> They go in the order they were placed and that is all there is to it.

Yes, when a link is added to a `nd.Links`, the `nd.Links` are considered unsorted. But the links will be sorted whenever a `nd.Marshal()`/`nd.Unmarshal()`/`nd.Encoded(force)` is called [1].

The name field in the link object is required for the links sort [2].

[1] https://github.com/ipfs/go-ipfs/blob/e8c753d2e52b9f6e47d7f13c6b6fcffd0888c548/merkledag/coding.go, and grep for where the `sort.Stable`'s are located.
[2] https://github.com/ipfs/go-ipfs/blob/e8c753d2e52b9f6e47d7f13c6b6fcffd0888c548/merkledag/node.go#L60

**Comment by daviddias** [comment]
I'm not 100% if I understand now. I remember talking with @whyrusleeping and the reason why we don't need offsets for leaf data nodes was because links were added in order as they were chunked. If we sort them by the name (which in case of data leaf nodes, they won't have any name), we will loose that order and won't be able to rebuild the file.

@vijayee as for the 'name' property, that is still useful because sometimes we need to wrap links (like a dag node that describes a directory)

**Comment by rht** [comment]
> If we sort them by the name (which in case of data leaf nodes, they won't have any name), we will loose that order and won't be able to rebuild the file.

`sort.Stable` retains the order of elements with the same name. And so the data leaf nodes with name `""` get grouped together, but still ordered in the sequence they were chunked.

**Comment by vijayee** [comment]
GH-23 should fix the problem
