### ISSUE TITLE
State of the branches

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-merkle-dag#9]
@vijayee Could you tell me what is the state of https://github.com/vijayee/js-ipfs-merkle-dag/branches and what do they have? Thank you

**Comment by vijayee** [comment]
FixDagServiceAndBatches should be closed and merged. Traversals I'm still working on. Traversals has DFS and BFS but needs modification to be able to perform operations on node data in pre and post orders. Technically this may not be needed considering its an iterator that passes out the data to be used as one sees fit but the go implementation has this capability. I dunno nothin' bout those other branches
